node{

        stage ('Generate Build Version') {
                echo 'Generating Provar Version...'
                env.BN = VersionNumber([
                        versionNumberString :'${BUILD_MONTH}.${BUILDS_TODAY,XX}.${BUILDS_ALL_TIME,XX}', 
                        projectStartDate : '2018-10-10', 
                        versionPrefix : ''
                ])
                println 'Provar Build Version Created: ' + env.BN
        }
        
        stage ('Git Checkout') {
                withCredentials([[$class: 'UsernamePasswordMultiBinding', credentialsId: 'ProvarGitCredentials',
                    usernameVariable: 'USERNAME', passwordVariable: 'PASSWORD']]) {
                    bat '''
                        C:
                        cd C:/Users/Administrator/git/Provar
                        
                        echo 'Resetting release branch: %RELEASE_BRANCH%'
                        git reset --hard %RELEASE_BRANCH%
                        
                        echo 'Pulling Provar repo'
                        git pull "https://%USERNAME%:%PASSWORD%@github.com/pnoffke/Provar.git" %RELEASE_BRANCH%
                        
                        cd C:/Users/Administrator/git/ProvarSF
                        
                        echo 'Resetting release branch: %RELEASE_BRANCH%'
                        git reset --hard %RELEASE_BRANCH%
                        
                        echo 'Pulling ProvarSF repo'
                        git pull "https://%USERNAME%:%PASSWORD%@github.com/pnoffke/ProvarSF.git" %RELEASE_BRANCH%
                        
                        '''
                }
        }
        
        stage ('Update Versions') {
                echo 'Updating versions'
        }
        
        stage ('Run Tests') {
                echo 'Running tests'
        }
        
        stage ('Tyco Build') {
                echo 'Building provar'
        }
        
        stage ('Generate Installers') {
                echo 'Creating installers for provar'
        }
}
