node{

        stage ('Generate Build Version') {
                echo 'Generating Provar Version...{Major.Minor.Build.Revision}'
                env.BUILD_NUMBER = VersionNumber([
                        versionNumberString :'${MAJOR.MINOR.BUILD}.${BUILDS_ALL_TIME,XX}', 
                        projectStartDate : '2018-10-10', 
                        versionPrefix : ''
                ])
                println 'Provar Build Version Created: ' + env.BUILD_NUMBER
        }
        
        stage ('Git Checkout') {
                withCredentials([[$class: 'UsernamePasswordMultiBinding', credentialsId: 'ProvarGitCredentials',
                    usernameVariable: 'USERNAME', passwordVariable: 'PASSWORD']]) {
                    bat '''
                        C:
                        cd C:/Users/Administrator/git/Provar
                        
                        echo 'Resetting release branch: %RELEASE_BRANCH%'
                        git reset --hard %RELEASE_BRANCH%
                        
                        echo 'Pulling Provar repo'
                        git pull "https://%USERNAME%:%PASSWORD%@github.com/pnoffke/Provar.git" %RELEASE_BRANCH%
                        
                        cd C:/Users/Administrator/git/ProvarSF
                        
                        echo 'Resetting release branch: %RELEASE_BRANCH%'
                        git reset --hard %RELEASE_BRANCH%
                        
                        echo 'Pulling ProvarSF repo'
                        git pull "https://%USERNAME%:%PASSWORD%@github.com/pnoffke/ProvarSF.git" %RELEASE_BRANCH%
                        
                        '''
                }
        }
        
        stage ('Update Versions') {
                echo 'Updating versions'
                bat '''
                        C:
                        cd C:/eclipse-oxygen-64-4.7.1a
                        
                        eclipsec -nosplash -application org.eclipse.ant.core.antRunner -Dbuild.version=%BUILD_NUMBER% -Dforcedotcom.apis=%FORCEDOTCOM.APIS% -Dforcedotcom.ui=%FORCEDOTCOM.UI% -Dforcedotcom.feature=%FORCEDOTCOM.FEATURE% -f %PROVAR_BUILD_SCRIPT_PATH%/ant-version-update.xml update-build-version
                        eclipsec -nosplash -application org.eclipse.ant.core.antRunner -Dbuild.version=%BUILD_NUMBER% -Dforcedotcom.apis=%FORCEDOTCOM.APIS% -Dforcedotcom.ui=%FORCEDOTCOM.UI% -Dforcedotcom.feature=%FORCEDOTCOM.FEATURE% -f %PROVAR_BUILD_SCRIPT_PATH%/ant-version-update.xml update-versions-pom
                        eclipsec -nosplash -application org.eclipse.ant.core.antRunner -Dbuild.version=%BUILD_NUMBER% -Dforcedotcom.apis=%FORCEDOTCOM.APIS% -Dforcedotcom.ui=%FORCEDOTCOM.UI% -Dforcedotcom.feature=%FORCEDOTCOM.FEATURE% -f %PROVAR_BUILD_SCRIPT_PATH%/ant-version-update.xml update-versions-manifest
                        
                        
                        
                '''
        }
        
        stage ('Run Tests') {
                echo 'Running tests'
        }
        
        stage ('Tyco Build') {
                echo 'Building provar'
                bat '''
                        C:
                        cd C:/Users/Administrator/git/Provar/Java/com.provar.build
                        mvn clean install -Declipse.install.loc=C:/eclipse-oxygen-64-4.7.1a
                '''
        }
        
        stage ('Generate Installers') {
                echo 'Creating installers for provar'
        }
}
